### ISSUE TITLE
[1.19.2] Crash with Ender Phasing effect

### ISSUE THREAD

**Issue by Pipsqueak737** [Ax3dGaming/EndersDelight#2]
The game crashes whenever a food is eaten that gives the Ender Phasing effect.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-03-02 15:35:52
Description: Ticking player

java.lang.ClassCastException: class java.util.Random cannot be cast to class net.minecraft.util.RandomSource (java.util.Random is in module java.base of loader 'bootstrap'; net.minecraft.util.RandomSource is in module minecraft@1.19.2 of loader 'TRANSFORMER' @c269425)
	at com.axedgaming.endersdelight.effect.PhasingEffect.m_6742_(PhasingEffect.java:29) ~[endersdelight-1.19-1.0.1.jar%23154!/:1.19-1.0.1] {re:classloading}
	at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:187) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:160) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntity.java:745) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:418) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2252) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.axedgaming.endersdelight.effect.PhasingEffect.m_6742_(PhasingEffect.java:29) ~[endersdelight-1.19-1.0.1.jar%23154!/:1.19-1.0.1] {re:classloading}
	at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:187) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:160) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:fml:forge:potion}
	at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntity.java:745) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:418) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2252) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 205
	Entity Name:
	Entity's Exact location: 9.15, 71.00, 20.00
	Entity's Block location: World: (9,71,20), Section: (at 9,7,4 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by Ax3dGaming** [comment]
I check this today, thanks for your report
